# Generated by Django 6.0.5 on 2026-05-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuzanne_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('collection', 'name')},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('collection', 'name'), ('collection', 'slug')},
        ),
    ]
