# Generated by Django 6.0.5 on 2026-05-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zuzanne_app', '0002_alter_category_unique_together_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='category',
        ),
        migrations.DeleteModel(
            name='GalleryCategory',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
