# Generated by Django 6.0.3 on 2026-06-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuzanne_app', '0003_remove_galleryimage_category_delete_gallerycategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('source_page', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking Enquiry',
                'verbose_name_plural': 'Booking Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
