# Generated by Django 6.0.3 on 2026-06-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuzanne_app', '0004_bookingenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingenquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
