# Generated by Django 6.0.3 on 2026-07-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuzanne_app', '0005_bookingenquiry_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comboset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='combo_items/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='zuzanne_app.product')),
            ],
        ),
    ]
