# Generated by Django 5.2.15 on 2026-07-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuzanne_app', '0006_comboset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='combo_items/'),
        ),
    ]
