# Generated by Django 5.2.15 on 2026-07-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuzanne_app', '0007_alter_comboset_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comboset',
            name='product',
        ),
        migrations.AddField(
            model_name='comboset',
            name='products',
            field=models.ManyToManyField(related_name='combo_items', to='zuzanne_app.product'),
        ),
    ]
